### ISSUE TITLE
Shortlist (until I learn how to push/pull)

### ISSUE THREAD

**Issue by jawadakhan97** [crftbt/PortableLaptops#1]
Most of the stuff I saw while browsing an RSS feed at liliputing.com, they have a [mini-laptop](https://liliputing.com/tag/mini-laptop/) section. Not all of this stuff is relevant... it's what first came to mind

### List
* MNT Pocket Reform [link](https://www.crowdsupply.com/mnt/pocket-reform)
* ITX Laptop (DIY) [link](https://liliputing.com/lilbits-this-diy-itx-laptop-is-ridiculous-in-the-best-way-possible/)

**Comment by crftbt** [comment]
Feel free to submit a pull request at any time. :)
